# Generated by Django 3.1.5 on 2021-02-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
